### ISSUE TITLE
SwitchDevice is deprecated

### ISSUE THREAD

**Issue by kjetilpp** [cagnulein/switchbot_press#7] opened 2021-08-30 12:40 UTC
Hello! 
In my HassIO log i see 
"Logger: homeassistant.components.switch
Source: components/switch/__init__.py:130
Integration: Bryter (documentation, issues)
First occurred: 14:24:31 (1 occurrences)
Last logged: 14:24:31

SwitchDevice is deprecated, modify SwitchBot_press to extend SwitchEntity"

For your information :) 
![Capture](https://user-images.githubusercontent.com/5620578/131340404-28e2aa29-62c4-44e5-9394-ea48efccfacb.PNG)

**Comment by cagnulein** [comment] 2021-08-30 12:45
duplicate of #2

**Closed as completed by cagnulein** 2021-08-30 12:45 UTC
